<?php
// To minimize the setup work use this modified configuration, which will insert the values out of the Phenotype-Configuration

require ("../../../../_config.inc.php");

// This file is automatically generated and modified by phpMyBackupPro v.1.8

$CONF['sitename']="Phenotype";
$CONF['lang']="english";
$CONF['import_error']="1";
$CONF['no_login']="0";
$CONF['login']="0";
$CONF['dir_backup']="0";
$CONF['dir_rec']="1";
$CONF['ftp_use']="0";
$CONF['ftp_pasv']="1";
$CONF['email_use']="0";
$CONF['ftp_del']="1";
$CONF['ftp_server']="";
$CONF['ftp_user']="";
$CONF['sql_passwd']="";
$CONF['sql_host']=DATABASE_SERVER;
$CONF['sql_user']=DATABASE_USER;
$CONF['sql_db']=DATABASE_NAME;
$CONF['ftp_passwd']="";
$CONF['ftp_path']="";
$CONF['ftp_port']="21";
$CONF['email']="";
$CONF['date']="%x %X";
$CONF['del_time']="7";
$CONF['del_number']="5";
$CONF['timelimit']="0";
$CONF['confirm']="1";
$CONF['stylesheet']="standard";


?>